[0.077s] Invoking command in '/home/ffelix07/Documents/LabRemo/Orchestrator/ros2_labremoto/build/my_mas': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/ffelix07/Documents/LabRemo/Orchestrator/ros2_labremoto/install/py_pubsub:/home/ffelix07/Documents/LabRemo/Orchestrator/ros2_labremoto/install/nodes_comunication:/home/ffelix07/Documents/LabRemo/Orchestrator/ros2_labremoto/install/hardware:/opt/ros/humble /usr/bin/cmake --build /home/ffelix07/Documents/LabRemo/Orchestrator/ros2_labremoto/build/my_mas -- -j4 -l4
[0.148s] -- Found ament_cmake: 1.3.5 (/opt/ros/humble/share/ament_cmake/cmake)
[0.860s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.872s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.881s] -- Found rosidl_adapter: 3.1.5 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.988s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[1.114s] -- Found geometry_msgs: 4.2.3 (/opt/ros/humble/share/geometry_msgs/cmake)
[2.094s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[2.094s]   execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name my_mas
[2.095s]   --arguments-file
[2.095s]   /home/ffelix07/Documents/LabRemo/Orchestrator/ros2_labremoto/build/my_mas/rosidl_adapter__arguments__my_mas.json
[2.095s]   --output-dir
[2.095s]   /home/ffelix07/Documents/LabRemo/Orchestrator/ros2_labremoto/build/my_mas/rosidl_adapter/my_mas
[2.096s]   --output-file
[2.096s]   /home/ffelix07/Documents/LabRemo/Orchestrator/ros2_labremoto/build/my_mas/rosidl_adapter/my_mas.idls)
[2.096s]   returned error code 1:
[2.097s] 
[2.097s]   Traceback (most recent call last):
[2.097s] 
[2.098s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[2.098s]       return _run_code(code, main_globals, None,
[2.099s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[2.099s]       exec(code, run_globals)
[2.100s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[2.100s]       sys.exit(main())
[2.101s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[2.101s]       abs_idl_file = convert_to_idl(
[2.101s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 24, in convert_to_idl
[2.102s]       return convert_srv_to_idl(
[2.102s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/srv/__init__.py", line 28, in convert_srv_to_idl
[2.103s]       srv = parse_service_string(package_name, input_file.stem, content)
[2.103s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 859, in parse_service_string
[2.103s]       request_message = parse_message_string(
[2.104s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 544, in parse_message_string
[2.104s]       msg = MessageSpecification(pkg_name, msg_name, fields, constants)
[2.104s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 388, in __init__
[2.105s]       self.base_type = BaseType(
[2.105s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
[2.105s]       raise InvalidResourceName(
[2.105s] 
[2.106s]   rosidl_adapter.parser.InvalidResourceName: 'Load_file_Request' is an
[2.106s]   invalid message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[2.111s] 
[2.113s] Call Stack (most recent call first):
[2.114s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[2.114s]   CMakeLists.txt:14 (rosidl_generate_interfaces)
[2.114s] 
[2.115s] [0m
[2.115s] -- Configuring incomplete, errors occurred!
[2.115s] See also "/home/ffelix07/Documents/LabRemo/Orchestrator/ros2_labremoto/build/my_mas/CMakeFiles/CMakeOutput.log".
[2.116s] gmake: *** [Makefile:747: cmake_check_build_system] Error 1
[2.116s] Invoked command in '/home/ffelix07/Documents/LabRemo/Orchestrator/ros2_labremoto/build/my_mas' returned '2': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/ffelix07/Documents/LabRemo/Orchestrator/ros2_labremoto/install/py_pubsub:/home/ffelix07/Documents/LabRemo/Orchestrator/ros2_labremoto/install/nodes_comunication:/home/ffelix07/Documents/LabRemo/Orchestrator/ros2_labremoto/install/hardware:/opt/ros/humble /usr/bin/cmake --build /home/ffelix07/Documents/LabRemo/Orchestrator/ros2_labremoto/build/my_mas -- -j4 -l4
